
image:
  repository: adminer
  tag: 4.7.6-standalone
ports: 
- containerPort: 8080

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "250m"

# Enable or disable optional resources
createConfigMap: false
createPV: false
createPVC: false

service:
  name: adminer   
  type: ClusterIP  # Change to NodePort for external access
  port: 8080       # Default port exposed by the service
  targetPort: 8080 # Default target port for the container

# Set number of replicas (default: 1)
replicas: 1

