
image:
  repository: wkrzywiec/kanban-app
  tag: k8s
ports: 
- containerPort: 8080

resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "232Mi"
    cpu: "500m"

# Enable or disable optional resources
createConfigMap: true
createPV: false
createPVC: false

config:
  POSTGRES_DB: kanban
  POSTGRES_USER: kanban
  POSTGRES_PASSWORD: kanban
  DB_SERVER: postgres

service:
  name: kanban-app  
  type: ClusterIP  # Change to NodePort for external access
  port: 8080       # Default port exposed by the service
  targetPort: 8080 # Default target port for the container

# Set number of replicas (default: 1)
replicas: 1

