adminUser: admin
adminPassword: admin

service:
  type: NodePort
  nodePort: 30030

ingress:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.default.svc.cluster.local
        access: proxy
        isDefault: true

persistence:
  enabled: false

dashboardProviders: {}
dashboards: {}
