# Default values for kanban-tp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# These can be overridden by the user during installation


image:
  repository: postgres
  tag: 9.6-alpine
ports: 
- containerPort: 5432

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "250m"

config:
  POSTGRES_DB: kanban
  POSTGRES_USER: kanban
  POSTGRES_PASSWORD: kanban

# Enable or disable optional resources
createConfigMap: true
createPV: true
createPVC: true

pv:
  capacity: 200Mi
  hostPath: "/tmp/data"
  storageClassName: ""

pvc:
  storageClassName: ""
  requests:
    storage: 200Mi

service:
  name: postgres   
  type: ClusterIP  # Change to NodePort for external access
  port: 5432       # Default port exposed by the service
  targetPort: 5432 # Default target port for the container

# Set number of replicas (default: 1)
replicas: 1
